---
title: "MERS Data Analysis"
author: "Megan Lott"
date: "May 15, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

## Introduction

This is the final exercise in the Compuational Workshop taught through UGA IDEAS Program in the Odum School of Ecology. In this exercise, we will analyze a data set on the spread of Middle East Respiratory
Syndrome Corona Virus (MERS-CoV) compiled and made available by Andrew Rambaut on his Github site. 

```{r Lib Load}
library(lubridate)
library(ggplot2)
library(plotly)
```


##Load Data 
```{r Load Data}
setwd("C:/Users/mel13212/Desktop/mers")
mers <- read.csv('cases.csv')
```


## Data Cleaning 
```{r Clean Data}
mers$hospitalized[890] <- c('2015-02-20')
mers <- mers [-471,]
mers$onset2 <- ymd(mers$onset)
mers$hospitalized2 <- ymd(mers$hospitalized)
class(mers$onset2)
day0 <- min(na.omit(mers$onset2))
mers$epi.day <- as.numeric(mers$onset2 - day0)
```

## Data Analysis 
```{r Data Analysis}
ggplot(data=mers) + 
  geom_bar(mapping=aes(x=epi.day, fill=country)) + 
  labs(x = 'Epidemic Day', y = 'Case Count', title = 'Global Count of MERS Cases by Date of Symptom Onset', 
         caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")
         
         
#calculate the raw infectious period
mers$infectious.period <- mers$hospitalized2-mers$onset2
class(mers$infectious.period)
mers$infectious.period <- as.numeric(mers$infectious.period, units = "days")


ggplot(data=mers) + 
  geom_histogram(aes(x=infectious.period)) + 
  labs(x = 'Infectious Period', y = 'Frequency', title = 'Distribution of Calculated MERS Infectious Period', 
       caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")

mers$infectious.period2 <- ifelse(mers$infectious.period<0, 0, mers$infectious.period)
ggplot(data=mers) + 
  geom_histogram(aes(x=infectious.period2)) + 
  labs(x = 'Infectious Period', y = 'Frequency', title = 'Distribution of Calculated MERS Infectious Period (Positive Values Only)', 
       caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")

ggplot(data=mers) + 
  geom_density(mapping = aes(x=infectious.period2)) + 
  labs(x = 'Infectious Period', y = 'Frequency', title = 'Probability Density of MERS Infectious Period (Positive Values Only)', 
       caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")

ggplot(data=mers) + 
  geom_area(stat = 'bin', mapping = aes(x=infectious.period2)) + 
  labs(x = 'Infectious Period', y = 'Frequency', title = 'Area Plot for MERS Infectious Period (Positive Values Only)', 
       caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")

ggplot(data=mers) + 
  geom_dotplot( mapping = aes(x=infectious.period2)) + 
  labs(x = 'Infectious Period', y = 'Frequency', title = 'Area Plot for MERS Infectious Period (Positive Values Only)', 
       caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")

ggplot(data=mers) + 
  geom_bar(stat = 'bin', mapping = aes(x=infectious.period2)) + 
  labs(x = 'Infectious Period', y = 'Frequency', title = 'Area Plot for MERS Infectious Period (Positive Values Only)', 
       caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")
       
ggplot(data=mers, mapping=aes(x=epi.day, y=infectious.period2, fill=country, color=country)) +
  geom_point() + geom_smooth(method='loess')
  
  ggplot(data=mers, mapping=aes(x=epi.day, y=infectious.period2))+
  geom_point(mapping = aes(color=country)) + 
  facet_wrap(~ country) + 
  scale_y_continuous(limits = c(0,50)) +
  labs(x='Epidemic Day', y = 'Infectious Period', title = 'MERS Infectious Period (Positive Values Only) Over Time', caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")
  
  
ggplot(data=subset(mers, gender %in% c('M', 'F') & country %in% c('France', 'Iran', 'Italy', 'Jordan', 'KSA', 'Kuwait', 'Lebanon', 'Oman', 'Qatar', 'South Korea', 'Tunisia', 'UAE', 'UK', 'Yemen')), 
       mapping = aes(x=epi.day, y=infectious.period2)) +
  geom_point(mapping = aes(color=country)) + 
  facet_grid(gender ~ country) + 
  scale_y_continuous(limits = c(0,50)) +
  labs(x='Epidemic Day', y = 'Infectious Period', title = 'MERS Infectious Period by Gender and by Country (Positive Values Only) Over Time', caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")
  
ggplot(data=subset(mers, gender %in% c('M', 'F') & country %in% c('France', 'Iran', 'Italy', 'Jordan', 'KSA', 'Kuwait', 'Lebanon', 'Oman', 'Qatar', 'South Korea', 'Tunisia', 'UAE', 'UK', 'Yemen')), 
       mapping = aes(x=epi.day, y=infectious.period2)) +
  geom_point(mapping = aes(color=country)) + 
  facet_grid(gender ~ country) + 
  scale_y_continuous(limits = c(0,50)) +
  labs(x='Epidemic Day', y = 'Infectious Period', title = 'MERS Infectious Period by Gender and by Country (Positive Values Only) Over Time', caption = "Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")


epi.curve <- ggplot(data=mers) +
  geom_bar(mapping=aes(x=epi.day)) +
  labs(x='Epidemic day', y='Case count', title='Global count of MERS cases by date of symptom onset',
       caption="Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.csv")

ggplotly(epi.curve)

```
